theme:           jekyll-theme-cayman
title:           Affine Cipher
description:     My implementation of Affine Cipher with a simple and easy to use GUI
is_user_page:    false
is_project_page: true
show_downloads:  true
